version: '3.8'
services:
  heladera:
    build: ./heladeras
    env_file: .env
    container_name: heladera
    ports:
      - "8084:8084"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s

  sensor:
    build: ./sensor
    env_file: .env
    container_name: sensor
    ports:
      - "8089:8089"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 10s
      timeout: 5s
      retries: 6  
      start_period: 15s

networks:
  internal_network:
    driver: bridge
