version: '3.8'
services:
  metricas:
    build: ./metrics
    env_file: .env
    container_name: metrics
    ports:
      - "8081:8081"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s
      
  telegram:
    build: ./telegram
    env_file: .env
    container_name: telegram
    ports:
      - "8080:8080"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s
      
  vianda:
    build: ./viandas
    env_file: .env
    container_name: viandas
    ports:
      - "8082:8082"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s

  logistica:
    build: ./logistica
    env_file: .env
    container_name: logistica
    ports:
      - "8083:8083"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s
 
  heladera:
    build: ./heladeras
    env_file: .env
    container_name: heladera
    ports:
      - "8084:8084"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s

  colaborador:
    build: ./colaboradores
    env_file: .env
    container_name: colaborador
    ports:
      - "8085:8085"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s

networks:
  internal_network:
    driver: bridge
